### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by francislavoie**
Pretty good guide! I just wanted to fix some mistakes/inaccuracies where I could.

Let me know if you have any questions about these changes 👍

### CODE REVIEW

**Comment by DoTheEvo** [comment]
Looks great.
I am googling why `docker-compose logs` or `docker-compose exec` instead of simpler `docker logs` and `docker exec`.

https://docs.docker.com/compose/reference/exec/
https://docs.docker.com/compose/reference/logs/

exe seems to do the same. And benefits of logs from my testing is seeing logs of all containers, and 

and for logs it does show logs of all containers in the compose, but this is just caddy if we dont count example nginx or whois.

docker version being shorter working from wherever in the system

**Comment by francislavoie** [comment]
The main difference is that you gave the container the name `caddy`, but I removed that because if someone wanted to run another stack with Caddy involved, that might conflict. Better to docker-compose use the default name IMO. And in that case, the name won't be `caddy` so you wouldn't be able to use `docker <command> caddy` anymore, the `docker-compose` variants will use the right container if run in the same directory.

**Comment by DoTheEvo** [comment]
Ah yeah, that I definitely be changing back then.
Its their issue to solve on how they name their stuff and how to keep track of what containers are running.
And I believe it gives the warning if container of that name already exists, and it would only exist in that form only if they already use their own naming.

**Comment by francislavoie** [comment]
Sure :+1: 

`image` should stay `caddy` though btw, that's the official docker image, and `caddy/caddy` is the "official image from Caddy" but there's no guarantees around that one compared to the official docker one.

**Pull request merged**
